openapi: 3.0.1
info:
  title: Order Service API
  description: |
    Order Service API for E-commerce Microservices Platform.
    Handles order creation, retrieval, cancellation, and status updates.
  version: 1.0.0
  contact:
    name: Order Service Team
    email: order-team@ecommerce.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.ecommerce.com/api/v1
    description: Production server

tags:
  - name: Orders
    description: Order management operations

paths:
  /api/v1/orders:
    post:
      tags:
        - Orders
      summary: Create a new order
      description: Creates a new order with customer information, delivery address, and list of products
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid request data (validation error)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Bad Request"
                status: 400
                detail: "Validation failed: customerId must not be null"
                instance: "/api/v1/orders"
        '422':
          description: Business rule violation (e.g., insufficient stock)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Insufficient Stock"
                status: 422
                detail: "Product ID 550e8400-e29b-41d4-a716-446655440001 does not have enough stock to fulfill request."
                instance: "/api/v1/orders"
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - BearerAuth: []

  /api/v1/orders/{id}:
    get:
      tags:
        - Orders
      summary: Get order details by ID
      description: Retrieves detailed information about a specific order
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the order
          schema:
            type: string
            format: uuid
          example: "650e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Order details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Not Found"
                status: 404
                detail: "Order with ID 650e8400-e29b-41d4-a716-446655440000 not found"
                instance: "/api/v1/orders/650e8400-e29b-41d4-a716-446655440000"
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - BearerAuth: []

  /api/v1/orders/{id}/cancel:
    post:
      tags:
        - Orders
      summary: Cancel an order
      description: |
        Cancels an order if it has not been shipped yet.
        Orders with status SHIPPED or DELIVERED cannot be cancelled.
      operationId: cancelOrder
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the order to cancel
          schema:
            type: string
            format: uuid
          example: "650e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelOrderResponse'
        '404':
          description: Order not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Not Found"
                status: 404
                detail: "Order with ID 650e8400-e29b-41d4-a716-446655440000 not found"
                instance: "/api/v1/orders/650e8400-e29b-41d4-a716-446655440000/cancel"
        '422':
          description: Order cannot be cancelled (already shipped or delivered)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Cannot Cancel Order"
                status: 422
                detail: "Order with ID 650e8400-e29b-41d4-a716-446655440000 cannot be cancelled because it has been shipped"
                instance: "/api/v1/orders/650e8400-e29b-41d4-a716-446655440000/cancel"
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - BearerAuth: []

  /api/v1/orders/{id}/status:
    patch:
      tags:
        - Orders
      summary: Update order status
      description: Updates the status of an order (e.g., from PREPARING to SHIPPED, or SHIPPED to DELIVERED)
      operationId: updateOrderStatus
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the order
          schema:
            type: string
            format: uuid
          example: "650e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Order status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid status value
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Bad Request"
                status: 400
                detail: "Invalid status value. Allowed values are: PREPARING, SHIPPED, DELIVERED"
                instance: "/api/v1/orders/650e8400-e29b-41d4-a716-446655440000/status"
        '404':
          description: Order not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: "about:blank"
                title: "Not Found"
                status: 404
                detail: "Order with ID 650e8400-e29b-41d4-a716-446655440000 not found"
                instance: "/api/v1/orders/650e8400-e29b-41d4-a716-446655440000/status"
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - BearerAuth: []

components:
  schemas:
    OrderRequest:
      type: object
      required:
        - customerId
        - address
        - items
      properties:
        customerId:
          type: string
          format: uuid
          description: Unique identifier of the customer placing the order
          example: "123e4567-e89b-12d3-a456-426614174000"
        address:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          description: List of products to be ordered
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItemRequest'
          example:
            - productId: "550e8400-e29b-41d4-a716-446655440001"
              quantity: 2
            - productId: "550e8400-e29b-41d4-a716-446655440002"
              quantity: 1

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the order
          example: "650e8400-e29b-41d4-a716-446655440000"
        customerId:
          type: string
          format: uuid
          description: Unique identifier of the customer
          example: "123e4567-e89b-12d3-a456-426614174000"
        address:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          description: List of items in the order
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        status:
          $ref: '#/components/schemas/OrderStatus'
        totalAmount:
          type: number
          format: double
          description: Total amount of the order in the system currency
          example: 299.99
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the order was created
          example: "2026-01-21T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the order was last updated
          example: "2026-01-21T14:45:00Z"

    OrderItemRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
          format: uuid
          description: Unique identifier of the product
          example: "550e8400-e29b-41d4-a716-446655440001"
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Quantity of the product to order
          example: 2

    OrderItemResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the order item
          example: "750e8400-e29b-41d4-a716-446655440000"
        productId:
          type: string
          format: uuid
          description: Unique identifier of the product
          example: "550e8400-e29b-41d4-a716-446655440001"
        productName:
          type: string
          description: Name of the product
          example: "Wireless Mouse"
        quantity:
          type: integer
          format: int32
          description: Quantity of the product ordered
          example: 2
        unitPrice:
          type: number
          format: double
          description: Price per unit at the time of order
          example: 49.99
        totalPrice:
          type: number
          format: double
          description: Total price for this item (unitPrice × quantity)
          example: 99.98

    Address:
      type: object
      required:
        - street
        - city
        - postalCode
        - country
      properties:
        street:
          type: string
          description: Street address including building number
          example: "123 Main Street, Apt 4B"
          minLength: 1
          maxLength: 200
        city:
          type: string
          description: City name
          example: "Istanbul"
          minLength: 1
          maxLength: 100
        state:
          type: string
          description: State or province (optional)
          example: "Marmara"
          maxLength: 100
        postalCode:
          type: string
          description: Postal or ZIP code
          example: "34000"
          minLength: 1
          maxLength: 20
        country:
          type: string
          description: Country name or ISO code
          example: "Turkey"
          minLength: 1
          maxLength: 100

    OrderStatus:
      type: string
      enum:
        - PREPARING
        - SHIPPED
        - DELIVERED
        - CANCELLED
      description: |
        Current status of the order:
        - PREPARING: Order is being prepared for shipment
        - SHIPPED: Order has been shipped to the customer
        - DELIVERED: Order has been delivered to the customer
        - CANCELLED: Order has been cancelled
      example: "PREPARING"

    UpdateStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/OrderStatus'

    CancelOrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the cancelled order
          example: "650e8400-e29b-41d4-a716-446655440000"
        status:
          $ref: '#/components/schemas/OrderStatus'
        message:
          type: string
          description: Confirmation message
          example: "Order has been successfully cancelled"
        cancelledAt:
          type: string
          format: date-time
          description: Timestamp when the order was cancelled
          example: "2026-01-21T15:30:00Z"

    ProblemDetails:
      type: object
      description: RFC 7807 Problem Details for HTTP APIs
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type
          example: "about:blank"
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: "Bad Request"
        status:
          type: integer
          format: int32
          description: The HTTP status code
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: "Validation failed: customerId must not be null"
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          example: "/api/v1/orders"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token-based authentication

security:
  - BearerAuth: []
